#############################################################################
# Makefile for building: libqthtmc.so
# Generated by qmake (2.01a) (Qt 4.8.7) on: Wed Jun 13 18:08:18 2018
# Project:  ui.pro
# Template: app
# Command: /opt/qt4/bin/qmake -o Makefile ui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.8.7/mkspecs/linux-g++ -I. -I/opt/qt-4.8.7/include/QtCore -I/opt/qt-4.8.7/include/QtGui -I/opt/qt-4.8.7/include -I. -Isrc -I../htmc/src -I.
LINK          = g++
LFLAGS        = -fPIC -shared -Wl,-soname,libqthtmc.so -Wl,-O1 #-Wl,-rpath,/opt/qt4/lib
LIBS          = $(SUBLIBS)  -L/opt/qt4/lib -lQtGui -lQtCore -lpthread 
55AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/qt.cpp \
		src/qtsensoryregion.cpp \
		src/qthtm.cpp \
		src/qtunit.cpp moc_qt.cpp
OBJECTS       = qt.o \
		qtsensoryregion.o \
		qthtm.o \
		qtunit.o \
		moc_qt.o
DIST          = /opt/qt-4.8.7/mkspecs/common/unix.conf \
		/opt/qt-4.8.7/mkspecs/common/linux.conf \
		/opt/qt-4.8.7/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.7/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.7/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.7/mkspecs/qconfig.pri \
		/opt/qt-4.8.7/mkspecs/modules/qt_webkit.pri \
		/opt/qt-4.8.7/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.7/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.7/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.7/mkspecs/features/release.prf \
		/opt/qt-4.8.7/mkspecs/features/default_post.prf \
		/opt/qt-4.8.7/mkspecs/features/shared.prf \
		/opt/qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/qt-4.8.7/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.7/mkspecs/features/qt.prf \
		/opt/qt-4.8.7/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.7/mkspecs/features/moc.prf \
		/opt/qt-4.8.7/mkspecs/features/resources.prf \
		/opt/qt-4.8.7/mkspecs/features/uic.prf \
		/opt/qt-4.8.7/mkspecs/features/yacc.prf \
		/opt/qt-4.8.7/mkspecs/features/lex.prf \
		/opt/qt-4.8.7/mkspecs/features/include_source_dir.prf \
		ui.pro
QMAKE_TARGET  = libqthtmc.so
DESTDIR       = 
TARGET        = libqthtmc.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ui.pro  /opt/qt-4.8.7/mkspecs/linux-g++/qmake.conf /opt/qt-4.8.7/mkspecs/common/unix.conf \
		/opt/qt-4.8.7/mkspecs/common/linux.conf \
		/opt/qt-4.8.7/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.7/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.7/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.7/mkspecs/qconfig.pri \
		/opt/qt-4.8.7/mkspecs/modules/qt_webkit.pri \
		/opt/qt-4.8.7/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.7/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.7/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.7/mkspecs/features/release.prf \
		/opt/qt-4.8.7/mkspecs/features/default_post.prf \
		/opt/qt-4.8.7/mkspecs/features/shared.prf \
		/opt/qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/qt-4.8.7/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.7/mkspecs/features/qt.prf \
		/opt/qt-4.8.7/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.7/mkspecs/features/moc.prf \
		/opt/qt-4.8.7/mkspecs/features/resources.prf \
		/opt/qt-4.8.7/mkspecs/features/uic.prf \
		/opt/qt-4.8.7/mkspecs/features/yacc.prf \
		/opt/qt-4.8.7/mkspecs/features/lex.prf \
		/opt/qt-4.8.7/mkspecs/features/include_source_dir.prf \
		/opt/qt4/lib/libQtGui.prl \
		/opt/qt4/lib/libQtCore.prl
	$(QMAKE) -o Makefile ui.pro
/opt/qt-4.8.7/mkspecs/common/unix.conf:
/opt/qt-4.8.7/mkspecs/common/linux.conf:
/opt/qt-4.8.7/mkspecs/common/gcc-base.conf:
/opt/qt-4.8.7/mkspecs/common/gcc-base-unix.conf:
/opt/qt-4.8.7/mkspecs/common/g++-base.conf:
/opt/qt-4.8.7/mkspecs/common/g++-unix.conf:
/opt/qt-4.8.7/mkspecs/qconfig.pri:
/opt/qt-4.8.7/mkspecs/modules/qt_webkit.pri:
/opt/qt-4.8.7/mkspecs/features/qt_functions.prf:
/opt/qt-4.8.7/mkspecs/features/qt_config.prf:
/opt/qt-4.8.7/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.8.7/mkspecs/features/default_pre.prf:
/opt/qt-4.8.7/mkspecs/features/release.prf:
/opt/qt-4.8.7/mkspecs/features/default_post.prf:
/opt/qt-4.8.7/mkspecs/features/shared.prf:
/opt/qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/qt-4.8.7/mkspecs/features/warn_on.prf:
/opt/qt-4.8.7/mkspecs/features/qt.prf:
/opt/qt-4.8.7/mkspecs/features/unix/thread.prf:
/opt/qt-4.8.7/mkspecs/features/moc.prf:
/opt/qt-4.8.7/mkspecs/features/resources.prf:
/opt/qt-4.8.7/mkspecs/features/uic.prf:
/opt/qt-4.8.7/mkspecs/features/yacc.prf:
/opt/qt-4.8.7/mkspecs/features/lex.prf:
/opt/qt-4.8.7/mkspecs/features/include_source_dir.prf:
/opt/qt4/lib/libQtGui.prl:
/opt/qt4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ui.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/libqthtmc.so1.0.0 || $(MKDIR) .tmp/libqthtmc.so1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/libqthtmc.so1.0.0/ && $(COPY_FILE) --parents src/qt.h .tmp/libqthtmc.so1.0.0/ && $(COPY_FILE) --parents src/qt.cpp src/qtsensoryregion.cpp src/qthtm.cpp src/qtunit.cpp .tmp/libqthtmc.so1.0.0/ && (cd `dirname .tmp/libqthtmc.so1.0.0` && $(TAR) libqthtmc.so1.0.0.tar libqthtmc.so1.0.0 && $(COMPRESS) libqthtmc.so1.0.0.tar) && $(MOVE) `dirname .tmp/libqthtmc.so1.0.0`/libqthtmc.so1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/libqthtmc.so1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qt.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qt.cpp
moc_qt.cpp: src/qt.h
	/opt/qt4/bin/moc $(DEFINES) $(INCPATH) src/qt.h -o moc_qt.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qt.o: src/qt.cpp src/qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt.o src/qt.cpp

qtsensoryregion.o: src/qtsensoryregion.cpp src/qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsensoryregion.o src/qtsensoryregion.cpp

qthtm.o: src/qthtm.cpp src/qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qthtm.o src/qthtm.cpp

qtunit.o: src/qtunit.cpp src/qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtunit.o src/qtunit.cpp

moc_qt.o: moc_qt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qt.o moc_qt.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

