######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 12 08:23:41 2016
######################################################################

TEMPLATE = app
TARGET = libqthtmc.so
DEPENDPATH += . src
INCLUDEPATH += . src $$(HTMDIR)

# Input
HEADERS += src/qt.h
SOURCES += src/qt.cpp \
           src/qtsensoryregion.cpp \
           src/qthtm.cpp\
           src/qtunit.cpp
